# Generated by Django 4.1.2 on 2022-10-28 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="standort",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("address", models.CharField(max_length=200)),
                ("lat", models.DecimalField(decimal_places=8, max_digits=10)),
                ("lon", models.DecimalField(decimal_places=8, max_digits=11)),
            ],
        ),
    ]
