# Generated by Django 4.1.2 on 2022-10-29 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("restaurants", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="standort_restaurant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("restaurant_name", models.CharField(max_length=200)),
                ("address", models.CharField(max_length=200)),
                ("lat", models.DecimalField(decimal_places=8, max_digits=10)),
                ("lon", models.DecimalField(decimal_places=8, max_digits=11)),
            ],
        ),
        migrations.DeleteModel(
            name="standort",
        ),
    ]
