# Generated by Django 4.1 on 2022-12-13 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("restaurants", "0003_standort_restaurant_city_standort_restaurant_country"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="standort_restaurant",
            name="city",
        ),
    ]
