# Generated by Django 4.1 on 2022-12-13 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("restaurants", "0004_remove_standort_restaurant_city"),
    ]

    operations = [
        migrations.AddField(
            model_name="standort_restaurant",
            name="email",
            field=models.CharField(default="default value", max_length=200),
        ),
    ]
