# Generated by Django 4.1 on 2022-12-16 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("restaurants", "0006_standort_restaurant_phone"),
    ]

    operations = [
        migrations.AddField(
            model_name="standort_restaurant",
            name="validated",
            field=models.BooleanField(default=False),
        ),
    ]
