# Generated by Django 4.1 on 2022-12-16 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("restaurants", "0007_standort_restaurant_validated"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="standort_restaurant",
            name="validated",
        ),
        migrations.AddField(
            model_name="standort_restaurant",
            name="first_name",
            field=models.CharField(default="none", max_length=200),
        ),
        migrations.AddField(
            model_name="standort_restaurant",
            name="last_name",
            field=models.CharField(default="none", max_length=200),
        ),
    ]
