# Generated by Django 4.1 on 2022-12-16 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("restaurants", "0008_remove_standort_restaurant_validated_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="standort_restaurant",
            name="verified",
            field=models.BooleanField(default=False),
        ),
    ]
