# Generated by Django 4.1 on 2022-12-23 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("restaurants", "0009_standort_restaurant_verified"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="standort_restaurant",
            name="phone",
        ),
        migrations.AlterField(
            model_name="standort_restaurant",
            name="verified",
            field=models.BooleanField(default="default value"),
        ),
    ]
