# Generated by Django 4.1 on 2023-01-02 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("restaurants", "0010_remove_standort_restaurant_phone_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="standort_restaurant",
            name="menu",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="standort_restaurant",
            name="verified",
            field=models.BooleanField(default=False),
        ),
    ]
